# frozen_string_literal: true
# source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", "~> 231", group: :jekyll_plugins
gem 'jekyll-feed'
gem 'jekyll-readme-index'
gem 'jemoji'
gem 'webrick'

# gem "jekyll"
# gem "rails"
